### ISSUE TITLE
Audit server implementation unit and integration tests

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#1042]
## Summary

As a followup to #995 and #1038, we need to perform an audit of our server implementation tests. In #995, we refine our client tests to be more focused on testing endpoints and commands (i.e. not duplicating the test cases that should be covered elsewhere). With #1038, this issue should have been caught by our tests. 

While implementing #1021, I noticed several tests using an assumed key rather than using the key returned that is provided by `InsertReturningId`. I may have repeated this pattern in some of my updates as well, which could be the cause of the issue that went unnoticed. Another potential cause could have been a lack of scenarios such as creating multiple classes, projects, or batches, which is a separate issue that came up with #1032.
 
## Problem Definition

Our unit tests and integration tests should catch issues such as the two mentioned above.

## Proposal

Audit our unit and integration tests for the ecocredit server implementation and apply fixes:

- [x] audit core server implementation and apply fixes #893
- [x] audit basket server implementation and apply fixes #894
- [x] audit marketplace server implementation and apply fixes #895

For each of these items, we should make sure we are not assuming the key and using `InsertReturningId` and we should make sure we are providing scenarios with multiple classes, projects, and batches.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
Closing as msg server tests have been rewritten and reviewed as a part of #893, #894, and #895.
