### ISSUE TITLE
v5.0 Readiness Checklist

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#1456]
## Summary

This checklist is to be used for tracking the final internal audit of v5.0 changes prior to inclusion in a published release.

***Note: One of the goals of this upgrade is to have a stable major version that will allow us to move forward with a series of upgrades that do not introduce API or client breaking changes. We should keep this in mind during the audit process and make sure we are addressing potential API and client breaking changes prior to release.***

### Release Candidate Checklist

The following checklist should be gone through once the items listed in v5.0 Titicaca Upgrade (#972) have been completed. This audit should be performed directly on main and a release branch should only be created after the audit is complete.

- [x] API audit (at least 1 person)
  - [x] All Msg and Query methods are well-named and organized (@ryanchristo)
  - [x] All types and state objects are well-named and organized (@ryanchristo)
  - [x] All proto comments are up-to-date, informative, and accurate (@technicallyty)
    - #1556
    - #1559
    - #1560
  - [x] All proto message links are included in module specifications (@aleem1314) #1558 
- [x] Unit and integration tests (at least 1 person)
  - [x] `ecocredit.v1` unit tests for all messages with emphasis on new messages (@aleem1314 ) #1516 
  - [x] `ecocredit.v1` unit tests for all queries with emphasis on new queries (@aleem1314 ) #1527 
  - [x] `ecocredit.basket.v1` unit tests for all messages with emphasis on new messages (@aleem1314 ) #1528 
  - [x] `ecocredit.basket.v1` unit tests for all queries with emphasis on new queries (@aleem1314) #1528 
  - [x] `ecocredit.marketplace.v1` unit tests for all messages with emphasis on new messages (@aleem1314 )
  - [x] `ecocredit.marketplace.v1` unit tests for all queries with emphasis on new queries (@aleem1314 )
- [x] State machine audit (at least 2 people)
  - [x] Make sure state machine logic matches API documentation (@aleem1314 , @technicallyty) #1543 
    - [x] `x/ecocredit/base` all messages with emphasis on new messages
    - [x] `x/ecocredit/basket` all messages with emphasis on new messages
    - [x] `x/ecocredit/marketplace` all messages with emphasis on new messages
  - [x] Read through keeper code and verify correctness upon visual inspection (@aleem1314 , @technicallyty)
    - [x] `x/ecocredit/base` all messages with emphasis on new messages
    - [x] `x/ecocredit/basket` all messages with emphasis on new messages
    - [x] `x/ecocredit/marketplace` all messages with emphasis on new messages
  - [x] Ensure all state machine code which could be confusing is properly commented (@aleem1314 , @technicallyty)
    - [x] `x/ecocredit/base` all messages with emphasis on new messages
    - [x] `x/ecocredit/basket` all messages with emphasis on new messages
    - [x] `x/ecocredit/marketplace` all messages with emphasis on new messages
  - [x] Assess potential threats for each method and ensure that threats have been addressed sufficiently
  - [x] Assess potential risks of any new third party dependencies and decide whether a dependency audit is needed @aleem1314  #1578 
- [x] Completeness audit (at least 1 person)
  - [x] Genesis validation for all state (@aleem1314 )
  - [x] Genesis import and export of all state (@aleem1314 )
  - [x] Query methods for all state (@aleem1314)
  - [x] CLI methods for all messages (@aleem1314) 
- [x] Manual testing on a testnet after above items have been addressed (at least 2 people)
  - [x] All Msg methods have been tested (@aleem1314, @ryanchristo, @dpdanpittman)
    - https://hackmd.io/vcNbk99BTiWJ4cMtALSBOA?view
  - [x] All Query methods have been tested (@aleem1314, @ryanchristo, @dpdanpittman)
    - https://hackmd.io/vcNbk99BTiWJ4cMtALSBOA?view
  - [x] Genesis import and export has been tested (@aleem1314, @ryanchristo)
    - https://hackmd.io/vcNbk99BTiWJ4cMtALSBOA?view
    - https://github.com/regen-network/regen-ledger/issues/1660
  - [x] IBC and ICA testing (controller, host, fee, etc.) (@aleem1314, @ryanchristo)
    - https://github.com/aleem1314/ica-testing
    - https://hackmd.io/L4Ru-CeuQZ6VMMrBXYDHLA?view
    - https://hackmd.io/xfkQsLDHRVat8nLqtpsbOw?view
  - [x] Amino for `gov` and `group` with sdk `v0.46.7-regen-1` (@aleem1314)
    - https://github.com/aleem1314/group-gov-amino-testing
    - https://hackmd.io/Q-iN8S0sS-afyRpt8np6Xg
    - https://github.com/regen-network/regen-ledger/issues/1717
  - [x] Snapshots have  been tested with sdk `v0.46.7-regen-1` (@ryanchristo)
    - https://hackmd.io/Xspht7-USs-4rMIjffXdMA?view
  - [x] Gov proposal migration works with sdk `v0.46.7-regen-2` (@ryanchristo)
    - https://github.com/regen-network/cosmos-sdk/pull/51
    - https://hackmd.io/dQLSDStnSMGEnxp-ahXlvg

**Comment by aleem1314** [comment]
Add manual testing for Amino for `group` and `gov` messages. I am able to successfully execute `group` messages. 
I am getting following error for `gov` messages

```
"Error when broadcasting tx 194AED34FB434451732E1B3AB869EA42CC004C1631625F3E281CC25A831BC03E at height 0. Code: 4; Raw log: signature verification failed; please verify account number (8), sequence (2) and chain-id (testnet): unauthorized"
```

Here is the sample repo test amino signing https://github.com/aleem1314/group-gov-amino-testing

**Comment by ryanchristo** [comment]
I was able to reproduce the error: https://hackmd.io/Q-iN8S0sS-afyRpt8np6Xg. Looking into it.

**Comment by ryanchristo** [comment]
Closing as all items have been complete and release process has started.
