### ISSUE TITLE
Add additional indexes and queries to x/ecocredit module

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#167]
It would improve UX to be able to make the following queries:

- [x] credit batches by class - #885
- [x] credit batches by issuer - #955 
- [x] credit classes by admin https://github.com/regen-network/regen-ledger/pull/954
- [x] credit balances by account for all batch denoms #942 

We should do pagination the way it is done in the SDK.

**Comment by technicallyty** [comment]
I've done #885 as a separate RPC endpoint, but im wondering if it might be better to do it all under the existing `Batches` with a oneof for which specific field to query by (projectId, classId, issuer..) thoughts? @ryanchristo @aaronc

**Comment by ryanchristo** [comment]
We should avoid using `oneof` as far as I understand (see #790 and #872).

**Comment by ryanchristo** [comment]
I guess query will not be affected by this though.

**Comment by ryanchristo** [comment]
I think we should keep queries separate but we can discuss on our next product call as part of #909.

**Comment by ryanchristo** [comment]
`issuer` is part of `BatchInfo` in `v1alpha1` (live on chain) and I think it should be part of `v1` as well. Adding issuer will not add another state migration and I think removing it might have been a mistake or misunderstanding.

I would go with (re)adding an issuer field and index to `BatchInfo`.
