### ISSUE TITLE
v5.1 Readiness Checklist

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#1855]
## Comparison

https://github.com/regen-network/regen-ledger/compare/v5.0.0...release/v5.1.x

## Relevant Changes

- [x] https://github.com/regen-network/regen-ledger/pull/1785
- [x] https://github.com/regen-network/regen-ledger/pull/1789
- [x] https://github.com/regen-network/regen-ledger/pull/1799
- [x] https://github.com/regen-network/regen-ledger/pull/1812
- [x] https://github.com/regen-network/regen-ledger/pull/1837
- [x] https://github.com/regen-network/regen-ledger/pull/1841
- [x] https://github.com/regen-network/regen-ledger/pull/1842
- [x] https://github.com/regen-network/regen-ledger/pull/1851
- [x] https://github.com/regen-network/regen-ledger/pull/1856
- [x] https://github.com/regen-network/regen-ledger/pull/1857
- [x] https://github.com/regen-network/regen-ledger/pull/1864

## Manual Testing

- [x] create [testing branch](https://github.com/regen-network/regen-ledger/tree/ryan/v5.1.0-testing) with replace directives
- [x] Initial round of testing: https://hackmd.io/gTAvEb3PSOmG_ZsU0nkkLQ

## First Release Candidate

- [x] all relevant changes are included in the changelog
- [x] tag a new minor version for each go module (except app)
- [x] tag a release candidate (target date 03/24/23)

## Second Release Candidate

- [x] ~confirm basket date criteria (pending standards discussion)~
- [x] ~if applicable, update basket date criteria based on decision~
- [x] add governance message for updating basket date criteria
- [x] tag a new minor version for each go module (except app)
- [x] tag a release candidate (target date 03/28/23)

## Official Release

- [x] Final round of testing: https://hackmd.io/rcbLyWHHSuOJhJEcObYgig
- [x] tag an official release (target date 03/28/23)

## Following Release

- [x] update documentation build to use `release/v5.1.x` branch
- [x] add validator upgrade guide - https://github.com/regen-network/regen-ledger/pull/1869
- [x] add developer migration guide - https://github.com/regen-network/regen-ledger/pull/1870
- [x] update proto revision references - https://github.com/regen-network/regen-ledger/pull/1871
