### ISSUE TITLE
Ecocredit Module Readiness Checklist

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#350]
## x/ecocredit Module Readiness Checklist

This checklist is to be used for tracking the final internal audit of new Cosmos SDK modules prior to inclusion in a published release.

### Release Candidate Checklist

The following checklist should be gone through once the module has been fully implemented. This audit should be performed directly on `master`, or preferably on a `alpha` or `beta` release tag that includes the module.

The module **should not** be included in any Release Candidate tag until it has passed this checklist.

- [x] API audit (at least 1 person) (@ryanchristo)
  - [x] Are Msg and Query methods and types well-named and organized?
    - [x] #500
    - [x] #516
  - [x] Is everything well documented (inline godoc as well as [`/spec/` folder](https://github.com/cosmos/cosmos-sdk/blob/master/docs/spec/SPEC-SPEC.md) in module directory)
    - [x] spec docs #478
    - [x] proto comments #522
    - [x] inline godoc #552
- [x] State machine audit (at least 2 people) (@aleem1314- https://github.com/regen-network/regen-ledger/pull/492 , @technicallyty - https://github.com/regen-network/regen-ledger/pull/491)
  - [x] @technicallyty 
    - [x] Read through MsgServer code and verify correctness upon visual inspection
    - [x] Ensure all state machine code which could be confusing is properly commented
    - [x] Make sure state machine logic matches Msg method documentation
  - [x] @aleem1314 
    - [x] Ensure that all state machine edge cases are covered with tests and that test coverage is sufficient (at least 90% coverage on module code)
    - [x] Assess potential threats for each method including spam attacks and ensure that threats have been addressed sufficiently. This should be done by writing up threat assessment for each method
    - [x] Assess potential risks of any new third party dependencies and decide whether a dependency audit is needed (ORM AUDIT NEEDED)
  - [x] Followups to be addressed:
    - [x] get consensus around the % fee we should burn or are we just leaving it at 100%? #517
    - [x] CreateBatch, Send, Retire, and Cancel all require looping to some degree. Should we be charging some set gas per loop step? #519
    - [x] there is no check for metadata in ValidateBasic. Should this be validated at all? shouldn't we at least enforce a length? what if someone sent a tx with a HUGE amount of metadata? #520
- [x] #509
  - [x] Genesis import and export of all state
  - [x] Query services
  - [x] CLI methods
  - [x] All necessary migration scripts are present (if this is an upgrade of existing module)

### Published Release Checklist

After the above checks have been audited and the module is included in a tagged Release Candidate, the following additional checklist should be undertaken for live testing, and potentially a 3rd party audit (if deemed necessary):

- [ ] Testnet / devnet testing (2-3 people) (@assignee1, @assignee2, @assignee3)
  - [ ] All Msg methods have been tested especially in light of any potential threats identified
  - [ ] Genesis import and export has been tested
- [ ] Nice to have (and needed in some cases if threats could be high): Official 3rd party audit

**Comment by technicallyty** [comment]
Currently the credit class fee is being 100% burned. https://github.com/regen-network/regen-ledger/blob/master/x/ecocredit/server/fee.go#L25

discussion here: https://github.com/regen-network/regen-ledger/discussions/383

was there ever consensus around the % fee we should burn or are we just leaving it at 100%?

**Comment by technicallyty** [comment]
CreateBatch, Send, Retire, and Cancel all require looping to some degree. Should we be charging some set gas per loop step?
