### ISSUE TITLE
ORM Package Readiness Checklist (x/ecocredit only)

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#455]
## ORM Package Readiness Checklist

ORM is used by ecocredits, so we need the components of the ORM module that are used by x/ecocredit.

- [x] Good unit and integration test coverage for all state machine logic (@ruhatch)
- [x] #490 (@robert-zaremba)
  - [x] Are state machine related functions and types well-named and organized?
  - [x] Is everything well documented (godoc as well as README.md in module directory)

----

We should only perform the above steps for the code that is used in `x/ecocredit`, i.e.:
```
orm.PrimaryKeyed (interface)
orm.RowID (type/casting)
orm.NewPrimaryKeyTableBuilder (function)
orm.PrimaryKeyTableBuilder (type)
-> Build (method)
orm.PrimaryKeyTable (type)
-> Create (method)
-> Has (method)
-> GetOne (method)
-> Save (method)
-> PrefixScan (method)
orm.Table (type)
-> Create (method)
-> Has (method)
-> GetOne (method)
-> Save (method)
-> PrefixScan (method)
orm.Sequence (type)
-> NewSequence (method)
-> NextVal (method)
orm.Pagination (function)
orm.PrefixRange (function)
```

**Comment by ruhatch** [comment]
`x/ecocredit` uses:
```
orm.PrimaryKeyed (interface)
orm.RowID (type/casting)
orm.NewPrimaryKeyTableBuilder (function)
orm.PrimaryKeyTableBuilder (type)
-> Build (method)
orm.PrimaryKeyTable (type)
-> Create (method)
-> Has (method)
-> GetOne (method)
-> Save (method)
orm.Sequence (type)
-> NewSequence (method)
-> NextVal (method)
```

**Comment by ruhatch** [comment]
I think if we add some additional property testing for `Table`, `PrimaryKeyTable`, and `Sequence`, and fix the bugs that we find during that process, inc. #456, then we should be fairly confident in what we're using from `orm`.

**Comment by ruhatch** [comment]
With #451 we also need to audit:
```
orm.Pagination (function)
orm.PrimaryKeyTable.PrefixScan (method)
```

**Comment by blushi** [comment]
@robert-zaremba what about benchmark?

**Comment by robert-zaremba** [comment]
Let's discuss on Discord how we can do a benchmark.

**Comment by clevinson** [comment]
I just updated the requirements and removed external audit + benchmarks. If we want to reconsider those we should do so in the broader context of ORM package, and not within the context of this specific micro-audit (scoped just to x/ecocredit).

Also closing since all items have been addressed.
