### ISSUE TITLE
ORM package checklist

### ISSUE THREAD

**Issue by robert-zaremba** [regen-network/regen-ledger#489]
## ORM Package Readiness Checklist

ORM is used by ecocredits, so we need to audit it as well.

- [ ] Good unit and integration test coverage for all state machine logic (@assignee)
- [ ] Internal API audit (at least 1 person) (@assignee)
  - [ ] Are Msg and Query methods and types well-named and organized?
  - [ ] Is everything well documented (godoc as well as README.md in module directory)
- [ ] Internal state machine audit (at least 2 people) (@assignee1, @assignee2)
  - [ ] Read through code which is related to the state machine logic and verify correctness upon visual inspection
  - [ ] Ensure all state machine code which could be confusing is properly commented
  - [ ] Ensure that all state machine edge cases are covered with tests and that test coverage is sufficient
  - [ ] Assess potential threats for each method including spam attacks and ensure that threats have been addressed sufficiently. This should be done by writing up threat assessment for each method
  - [ ] Assess potential risks of any new third party dependencies and decide whether a dependency audit is needed
- [ ] Benchmark
- [ ] Nice to have (and needed in some cases if threats could be high): official 3rd party audit

**Comment by clevinson** [comment]
In our Ledger grooming call we had discussed only auditing hte compoennts of ORM that are used in ecocredit, and @ruhatch already took care of this in #455

Can we close this? If there are specific pieces you are wanting to work on (e.g. #490) can you open it as a sub-item in #455?
