### ISSUE TITLE
Epic: Basket Bridge for Klima

### ISSUE THREAD

**Issue by robert-zaremba** [regen-network/regen-ledger#630]
## Ethereum / Polygon smart contracts

- [ ] basket erc-20s
- [ ] fixed price store
- [ ] Sushiswap pools

## Ethereum self custody bridge

- [ ] multisig

## Regen Ledger Bridge

- [ ] Bridge reserve & Bridge lockup groups / multisig accounts.
    Bridge reserve is used to store tokens to be moved to Polygon. Bridge lockup is an account storing tokens which have been moved (minted) to Polygon.
- [ ] documentation

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned
