### ISSUE TITLE
Non-destructive blockchain upgrades

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#70]
# Acceptance Criteria

- [x] governance can coordinate a smooth chain upgrade at a specified block height without requiring chain dumps
- [x] upgrade daemon for smoothly handling upgrades
- [x] smooth upgrades can handle root multi store renames/deletions
- [x] support for recovering from upgrades that need to be aborted
- [x] backwards compatible upgrades for Tendermint (discussed with Ethan Buchman in Berlin and sounded feasible)

**Comment by aaronc** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [In-place upgrade handler for Cosmos SDK v0.36 #61](https://github.com/regen-network/regen-ledger/issues/61) | N/A | N/A | Open


###### do-not-edit-end-codetree-epic-issues
