### ISSUE TITLE
x/data v1 Readiness Checklist

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#714]
## x/data v1 Module Readiness Checklist

This checklist is to be used for tracking the final internal audit of new Cosmos SDK modules prior to inclusion in a published release.

### Release Candidate Checklist

The following checklist should be gone through once the module has been fully implemented. This audit should be performed directly on `master`, or preferably on a `alpha` or `beta` release tag that includes the module.

The module **should not** be included in any Release Candidate tag until it has passed this checklist.

- [x] API audit (at least 1 person) (@ryanchristo)
  - [x] Are Msg and Query methods and types well-named and organized?
    - #1156
  - [x] Is everything well documented (inline godoc as well as `/spec/` folder in module directory)
    - #1156
- [x] State machine audit (at least 2 people) (@ryanchristo, @aleem1314).
  - [x] Read through MsgServer code and verify correctness upon visual inspection
  - [x] Ensure all state machine code which could be confusing is properly commented
  - [x] Make sure state machine logic matches Msg method documentation
  - [x] Ensure that all state machine edge cases are covered with tests and that test coverage is sufficient (at least 90% coverage on module code)
  - [x] Assess potential threats for each method including spam attacks and ensure that threats have been addressed sufficiently. This should be done by writing up threat assessment for each method
  - [x] Assess potential risks of any new third party dependencies and decide whether a dependency audit is needed
- [x] Completeness audit, fully implemented with tests (at least 1 person) (@ryanchristo)
  - [x] ~Genesis import and export of all state~ n/a
  - [x] Query services
    - #1156
  - [x] CLI methods
    - #1156
  - [x] ~All necessary migration scripts are present (if this is an upgrade of existing module)~ n/a

### Published Release Checklist

After the above checks have been audited and the module is included in a tagged Release Candidate, the following additional checklist should be undertaken for live testing, and potentially a 3rd party audit (if deemed necessary):

- [x] Testnet / devnet testing (2-3 people) (@kaustubhkapatral, @aleem1314, @ryanchristo)
  - [x] All Msg methods have been tested especially in light of any potential threats identified
    - [x] Data is not anchored twice when data has already been anchored
    - [x] Data is anchored if not already anchored when calling `Attest` and `Register`
  - [x] Genesis import and export has been tested (@kaustubhkapatral)
- [ ] Nice to have (and needed in some cases if threats could be high): Official 3rd party audit

**Comment by ryanchristo** [comment]
:rocket:
