### ISSUE TITLE
x/ecocredit v1 Readiness Checklist

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#715]
## x/ecocredit v1 Module Readiness Checklist

This checklist is to be used for tracking the final internal audit of new Cosmos SDK modules prior to inclusion in a published release.

### Release Candidate Checklist

The following checklist should be gone through once the module has been fully implemented. This audit should be performed directly on `master`, or preferably on a `alpha` or `beta` release tag that includes the module.

The module **should not** be included in any Release Candidate tag until it has passed this checklist.

- [x] API audit (at least 1 person) (@ryanchristo)
  - [x] Are Msg and Query methods and types well-named and organized?
    - #1161
    - #1168
    - #1192
    - #1197
    - #1198
  - [x] Is everything well documented (inline godoc as well as `/spec/` folder in module directory)
- [x] State machine audit (at least 2 people) (@aleem1314, @technicallyty, @ryanchristo).
  - [x] Read through MsgServer code and verify correctness upon visual inspection
  - [x] Ensure all state machine code which could be confusing is properly commented
  - [x] Make sure state machine logic matches Msg method documentation
  - [x] Ensure that all state machine edge cases are covered with tests and that test coverage is sufficient (at least 90% coverage on module code)
      - #1155
      - #1160
      - #1170
      - #1202
  - [x] Assess potential threats for each method including spam attacks and ensure that threats have been addressed sufficiently. This should be done by writing up threat assessment for each method
  - [x] Assess potential risks of any new third party dependencies and decide whether a dependency audit is needed
- [x] State migration audit and testing using a temporary test network (@kaustubhkapatral, @aleem1314)
  - [x] Read through state migration and verify correctness upon visual inspection
  - [x] Spin up a temporary test network and populate with data and then perform upgrade with mainnet chain id
  - [x] Spin up a temporary test network and populate with data and then perform upgrade with redwood chain id
- [x] Completeness audit, fully implemented with tests (at least 1 person) (@aleem1314, @ryanchristo)
  - [x] Genesis import and export of all state
    - #1195
  - [x] Query services
      - #1168
      - #1178
      - #1197
      - #1198
  - [x] CLI methods
    - #1155
    - #1176
    - #1199
  - [x] All necessary migration scripts are present
    - #1180
    - #1185
    - #1188
    - #1205
    - #1209

### Published Release Checklist

After the above checks have been audited and the module is included in a tagged Release Candidate, the following additional checklist should be undertaken for live testing, and potentially a 3rd party audit (if deemed necessary):

- [x] Testnet / devnet testing (2-3 people) (@kaustubhkapatral , @aleem1314, @ryanchristo)
  - [x] All Msg methods have been tested especially in light of any potential threats identified (@ryanchristo, @aleem1314)
    - [x] Test bridge messages (@technicallyty @ryanchristo)
    - [x] Create sell order to place credits in escrow and then test `Msg/Send`, `Msg/Cancel`, `Msg/Retire`, etc. (@ryanchristo, @aleem1314)
    - [x] Make sure sell orders with an expiration are cancelled upon expiration and credits are unescrowed (@ryanchristo)
    - [x] Make sure new governance proposals (add credit type and allow denom) are working as expected (@ryanchristo)
  - [x] Genesis import and export has been tested (@kaustubhkapatral)
    - [x] Test export and genesis validation after migration and Msg methods have been tested (@kaustubhkapatral)
  - [x] State migration checks (@ryanchristo, @aleem1314)
    - [x] All manual operations produce expected result (i.e. `migrateDenomMetadata`, etc.)
    - [x] Check balance of community member account before and balance after upgrade (i.e. after `recoverFunds`)
- [ ] Nice to have (and needed in some cases if threats could be high): Official 3rd party audit

**Comment by ryanchristo** [comment]
:rocket:
