### ISSUE TITLE
Mainnet Launch Readiness

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#77]
These are the minimum things required for launch, they are not the minimum desired features (as we would like to launch with much more) but the minimum required features.

- [x] smooth chain upgrades (needs #70)
- [ ] community staking DAO support (needs cosmos-cg-key-management/cosmos-sdk#11)
- [x] protobuf encooding (needs #88)

These will allow us to:
* have an upgradeable blockchain that doesn't need to dump state/restart
* support community staking DAOs

The logic behind this is that we can launch sooner with a minimal feature set if we have an upgradeable chain, and then slowly add features as they are ready rather than delaying until we have everything that we want.

**Comment by aaronc** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/git-pull-request.svg) [167077825 swid #58](https://github.com/regen-network/regen-ledger/issues/58) | N/A | N/A | Merged


###### do-not-edit-end-codetree-epic-issues

**Comment by aaronc** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | State
----- | --------- | --------- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Permanently Locked accounts #188](https://github.com/regen-network/regen-ledger/issues/188) | N/A | N/A | Open


###### do-not-edit-end-codetree-epic-issues
