### ISSUE TITLE
Wire up new submodules to ecocredit module

### ISSUE THREAD

**Issue by technicallyty** [regen-network/regen-ledger#898]
## Summary

We currently have 3 submodules (`Core`, `Basket`, `Marketplace`) that are not currently fully wired into the ecocredit module. Feel free to add bullet points i may have missed.

## Proposal

- [x] embed the submodule keepers into the ecocredit `serverImpl` - #913 
- [x] ensure the new `PruneOrders` (in the `marketplace` submodule) is wired into `BeginBlocker`.  - #913 
- [ ] remove any files no longer used in the ecocredit module (multiple pull requests)
  - [x] migrate server implementation and remove unused files - #995
  - [x] migrate ecocredit utils to core and remove unused files - #1048
  - [ ] remove remaining v1alpha2 proto and implementation - #1063

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
